project:
  output-dir: _book-foc
  execute-dir: project

format:
  pdf:
    documentclass: book
    classoption: [10pt, pagesize, twoside]
    colorlinks: true # must be set in order for quarto to load dvipsnames in xcolor for book class ....
    papersize: a5
    keep-tex: true
    latex-output-dir: _latex-output
    linestretch: 1.09
    pdf-engine: lualatex # xelatex
    template-partials:
      - style-foc/passoptions.latex
      - style-foc/before-body.tex
    include-after-body: style-foc/foc-list.tex
    latex-clean: false
    geometry:
    - left=1.2cm
    - right=1.2cm
    - top=1.8cm
    - bottom=1.6cm
#    - marginparsep=0.2cm
#    - marginparwidth=4.4cm
    reference-location: block
    include-in-header: style-foc/preamble-foc.tex