project:
  output-dir: _book-foc
  execute-dir: project

format:
  pdf:
    documentclass: book
    classoption: [10pt, pagesize, twoside]
    colorlinks: true # must be set in order for quarto to load dvipsnames in xcolor for book class ....
    papersize: a5
    keep-tex: true
    latex-output-dir: _latex-output
    linestretch: 1.0
    pdf-engine: lualatex
    template-partials:
      - style/passoptions.latex
    include-after-body: style/foc-list.tex
    geometry:
    - left=1.2cm
    - right=1.2cm
    - top=1.8cm
    - bottom=1.8cm
#    - marginparsep=0.2cm
#    - marginparwidth=4.4cm
    reference-location: block
    include-in-header: style/preamble-foc.tex